apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crontab.name" . }}
  labels:
{{ include "crontab.label_base" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crontab.name" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "crontab.name" . }}
  apiGroup: rbac.authorization.k8s.io
