apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crontab.name" . }}
  labels:
{{ include "crontab.label_base" . | indent 4 }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
